spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Tangyongdong/configFile/
          search-paths: config-info
          default-label: master
          username: Tangyongdong
          password: Tyd123zxz